### ISSUE TITLE
How to Host the Server?

### ISSUE THREAD

**Issue by Star-Frog** [Wavesonics/GodotClientServer#3]
I have a problem hosting the server on Linux. I have W10. I downloaded the Oracle VR Box for Linux. There I redirected the port from my W10 IP to the Linux IP. I also redirected the IP from Windows to the Linux IP. The ports are already approved on both operating systems. Now I have started the server through the terminal. He starts up. But when I enter the IP address (from W10) in the client, it does not connect. Waiting time to eliminate: about 10-15 seconds. Did I forgot something? Can you help me? I really don't know what's wrong.

**Comment by Wavesonics** [comment]
I haven't tried with virtual box, but I doubt this is an issue with Godot or this template. My guess is it's just wonkyness from trying to network between the host and guest OS.

For my project I'm using WSL: https://docs.microsoft.com/en-us/windows/wsl/install-win10

It takes essentially no resources to run a WSL terminal, it's fully native, so it really is just running on your host OS because there is no VM.

**Comment by Star-Frog** [comment]
Can you tell me more about it?
How does the WSL setup work for the server? Is a server setup also available under W10? The sample project I uploaded (peer-to-peer) was just a quick test, sorry. Otherwise I would use a server-to-peer model. And have you tried this before with a Godot project?

**Comment by Wavesonics** [comment]
So the [README](https://github.com/Wavesonics/GodotClientServer/blob/master/README.md) goes into greater detail, but the gist of it is that you have two different exports, one for client and one for server. So you export the server, and then run it, and thats it, thats now running the server.

For a headless server, Godot currently only supports doing this on Linux, so you have to download their headless Linux binary (_link in the README_) and run that while pointing to a PCK you export from the project. And using WSL you can run that from linux headless binary right inside Windows.

**Comment by Star-Frog** [comment]
Hi, it's me again. Didn't have much time ... Anyway, I wanted to ask about the README file. It says the command (...) server.pck. Doesn't it mean (...) server.zip?

**Comment by Wavesonics** [comment]
you can export the data pack with either pck or zip. I usually do pck, but either should work.

**Comment by Wavesonics** [comment]
I'm going to close this one. Feel free to open another with any more specific questions you have.
